name: Process KiCad

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: Compile
  cancel-in-progress: true

jobs:
  ProcessKicad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Process
        run: |
          git config --global user.name 'gbg-with-joysticks'
          git config --global user.email 'gbg-with-joysticks@users.noreply.github.com'
          git pull

          docker pull kicad/kicad:9.0

            docker run --rm --user root --mount type=bind,source=${{ github.workspace }},target=/workspace kicad/kicad:9.0 /bin/bash -c "
              kicad-cli pcb render --output '/workspace/renders/top.jpg' --quality high --rotate '0,0,-90' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
              kicad-cli pcb render --output '/workspace/renders/back.jpg' --quality high --rotate '180,0,180' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
              kicad-cli pcb render --output '/workspace/renders/perspective1.jpg' --quality high --perspective --zoom 0.65 --rotate '315,0,45' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
              kicad-cli pcb render --output '/workspace/renders/perspective2.jpg' --quality high --perspective --zoom 0.65 --rotate '315,0,315' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
              kicad-cli sch export pdf --output '/workspace/schematic.pdf' /workspace/kicad/gbg-pcb.kicad_sch
              kicad-cli sch export bom /workspace/kicad/gbg-pcb.kicad_sch --output /workspace/PCB_production/BOM.csv --fields Reference,Value,Footprint,Manufacturer_Name,Manufacturer_Part_Number,digikey_part_number,mount_type
              kicad-cli pcb export gerbers --layers F.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts /workspace/kicad/gbg-pcb.kicad_pcb --output /workspace/PCB_production/gerbers
              kicad-cli pcb export drill /workspace/kicad/gbg-pcb.kicad_pcb --output /workspace/PCB_production/gerbers
              zip -r /workspace/PCB_production/gerbers.zip /workspace/PCB_production/gerbers
              rm -rf /workspace/PCB_production/gerbers
            "
            
          git add .
          git commit . -m "BOT process website" --allow-empty
          git push

          
          
