name: Process KiCad

on:
  workflow_dispatch:

concurrency:
  group: Compile
  cancel-in-progress: true

jobs:
  ProcessKicad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pull kicad docker
        run: |
          git config --global user.name 'gbg-with-joysticks'
          git config --global user.email 'gbg-with-joysticks@users.noreply.github.com'
          git pull

          docker pull kicad/kicad:9.0
      - name: process kicad
        run: |
          docker run --rm --user root --mount type=bind,source=${{ github.workspace }},target=/workspace kicad/kicad:9.0 /bin/bash -c "
            kicad-cli sch export pdf --output '/workspace/schematic.pdf' /workspace/kicad/gbg-pcb.kicad_sch
            kicad-cli sch export bom /workspace/kicad/gbg-pcb.kicad_sch --output /workspace/PCB_production/BOM.csv --fields 'Reference,Value,Footprint,Manufacturer_Name,Manufacturer_Part_Number,digikey_part_number,mount_type,\${QUANTITY}' --group-by Manufacturer_Part_Number --exclude-dnp
            kicad-cli pcb export gerbers --layers F.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts /workspace/kicad/gbg-pcb.kicad_pcb --output /workspace/PCB_production/gerbers
            kicad-cli pcb export drill /workspace/kicad/gbg-pcb.kicad_pcb --output /workspace/PCB_production/gerbers
            kicad-cli pcb export pos --output '/workspace/PCB_production/position.csv' --smd-only /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb export dxf --output '/workspace/PCB_production/soldermask.dxf' --layers F.Mask /workspace/kicad/gbg-pcb.kicad_pcb
            zip -r /workspace/PCB_production/gerbers.zip /workspace/PCB_production/gerbers
            rm -rf /workspace/PCB_production/gerbers
          "
            
          git add .
          git commit . -m "BOT process kicad" --allow-empty
          git push

      - name: process kicad
        run: |
          docker run --rm --user root --mount type=bind,source=${{ github.workspace }},target=/workspace kicad/kicad:9.0 /bin/bash -c "
            kicad-cli pcb render --output '/workspace/renders/top.jpg' --quality high --rotate '0,0,0' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb render --output '/workspace/renders/back.jpg' --quality high --rotate '180,0,180' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb render --output '/workspace/renders/perspective1.jpg' --quality high --perspective --zoom 0.65 --rotate '315,0,45' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
            kicad-cli pcb render --output '/workspace/renders/perspective2.jpg' --quality high --perspective --zoom 0.65 --rotate '315,0,315' --width 1000 --height 1000 /workspace/kicad/gbg-pcb.kicad_pcb
          "

          git add .
          git commit . -m "BOT render images" --allow-empty
          git push
