name: Process KiCad

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        git clone https://github.com/KiCad/kicad-docker.git
        cd kicad-docker
        docker build -t kicad:9.0-stable -f Dockerfile.9.0-stable .

    - name: Run with KiCad Docker image
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace kicad:9.0-stable /bin/bash -c "cd /workspace && 
          git config --global user.name 'gbg-with-joysticks' &&
          git config --global user.email 'gbg-with-joysticks@users.noreply.github.com' &&
          git pull &&

          kicad-cli pcb render --output 'renders/top.jpg' --quality high --rotate '0,0,-90' --width 1000 --height 1000 gbg-pcb.kicad_pcb &&
          kicad-cli pcb render --output 'renders/perspective1.jpg' --quality high --perspective --zoom 0.65 --rotate '-45,0,45' --width 1000 --height 1000 gbg-pcb.kicad_pcb &&
          kicad-cli pcb render --output 'renders/perspective2.jpg' --quality high --perspective --zoom 0.65 --rotate '-45,0,-45' --width 1000 --height 1000 gbg-pcb.kicad_pcb &&

          git commit . -m 'BOT add generated files' --allow-empty &&
          git push
          "
